#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 13:00:00
#SBATCH -J megahit
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Load modules
module load bioinfo-tools megahit

#DATA
SEQDIR="/proj/genomeanalysis2023/nobackup/work/claudg/raw_data/DNA_trimmed"
OUTDIR="/home/claudg/genome-project/analyses/DNA_assembled_megahit"

#assembly 1
megahit --k-min 20 --k-max 105 --k-step 10 --kmin-1pass -1 $SEQDIR/SRR4342129_1.paired.trimmed.fastq.gz -2 $SEQDIR/SRR4342129_2.paired.trimmed.fastq.gz -o $OUTDIR/3

#assembly 2
megahit --k-min 20 --k-max 105 --k-step 10 --kmin-1pass -1 $SEQDIR/SRR4342133_1.paired.trimmed.fastq.gz -2 $SEQDIR/SRR4342133_2.paired.trimmed.fastq.gz -o $OUTDIR/4


