#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 13:00:00
#SBATCH -J megabat_binning
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Define input dir paths
export DATA="/home/claudg/genome-project/analyses"
export IN1=$DATA/DNA_assembled_megahit/1
export IN2=$DATA/DNA_assembled_megahit/2

#Load program
module load bioinfo-tools
module load MetaBat

#Create and define output dir
cd $DATA
mkdir $DATA/DNA_bins_metabat
export OUT=$DATA/DNA_bins_metabat

metabat -i $IN1/final.contigs.fa -o $OUT/SRR4342129_bins
metabat -i $IN2/final.contigs.fa -o $OUT/SRR4342133_bins
