#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 13:00:00
#SBATCH -J annotation-prokka
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Load modules
module load bioinfo-tools
module load prokka

#Load path to input data dir and output dir
export DATA="/home/claudg/genome-project/analyses"
export INDIR=$DATA/3_DNA_bins_metabat
export OUTDIR=$DATA/5_DNA_prokka


for bins in $INDIR/1/*.fa
do
echo $bins
prokka --metagenome --cpus 2 $bins --force --outdir $OUTDIR/1/"$bins"_ann.out
done

for bins in $INDIR/2/*.fa
do
echo $bins
prokka --metagenome --cpus 2 $bins --force --outdir $OUTDIR/2/"$bins"_ann.out
done
