#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 13:00:00
#SBATCH -J annotation-prokka
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Load modules
module load bioinfo-tools
module load prokka

#Load path to input data dir and output dir
export DATA="/domus/h1/claudg/genome-project/analyses"
export INDIR=$DATA/DNA_bins_metabat
export OUTDIR=$DATA/DNA_annotation_prokka


cd $INDIR/1
	for bins in *
		do
		if [ -f "$bins" ]; then
    		echo "Processing: $bins"
    
    		# Remove the file extension from the filename
    		bin="${bins%.*}"
		echo $bin
    
    # Run Prokka with the corrected variables
    		prokka --addgenes --metagenome --cpus 2 --prefix "$bin" --force --outdir $OUTDIR/1 $bins
    
    		echo "Finished processing: $bins"
  	else
    		echo "Skipping non-file: $bins"
  	fi
done

cd $INDIR/2
	for bins in *
		do
		if [ -f "$bins" ]; then
    		echo "Processing: $bins"
    
    		# Remove the file extension from the filename
    		bin="${bins%.*}"
		echo $bin
    
    		# Run Prokka with the corrected variables
    		prokka --addgenes --metagenome --cpus 2 --prefix "$bin" --force --outdir $OUTDIR/2 $bins
    
    		echo "Finished processing: $bins"
  	else
    		echo "Skipping non-file: $bins"
  	fi
done
