#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -J phylophlan
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Load modules
module load bioinfo-tools phylophlan/0.99
module unload python
#module load python 2.7.15 
module load biopython/1.73 
module load FastTree/2.1.10
module load usearch/5.2.32 
module load muscle/3.8.31

#Make directory look like installation dir
export DIR="/home/claudg/genome-project/analyses"
export OUTDIR="/proj/genomeanalysis2023/nobackup/work/claudg"
mkdir -p $OUTDIR/8_DNA_phylophlan
export PROJ=$OUTDIR/8_DNA_phylophlan
export INDIR=$DIR/DNA_annotation_prokka
mkdir -p $PROJ/input
mkdir -p $PROJ/output
mkdir -p $PROJ/data/ppaalns
mkdir -p $PROJ/taxcuration

#Load symlink
ln -s -f /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/*.bz2 $PROJ/data/
ln -s -f /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppaalns/*.bz2 $PROJ/data/ppaalns/

ln -s -f /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppafull.tax.txt $PROJ/data/

ln -s -f /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/taxcuration/ $PROJ/taxcuration

mkdir -p $PROJ/input/1
mkdir -p $PROJ/input/2
mkdir -p $SNIC_TMP/1 
mkdir -p $SNIC_TMP/2

cd $INDIR/1
for bin in S*.faa
do
	cp -r $bin $SNIC_TMP/1
	cd $SNIC_TMP/1
	name=$($bin%%.*)
	echo "$name"
	mv $bin $name.fa
	cp -r $name.fa $PROJ/input/1	
done

cd $INDIR/2
for bin in S*.faa
do
	cp -r $bin $SNIC_TMP/2
	cd $SNIC_TMP/2
	name=$($bin%%.*)
	mv $bin $name.fa
	cp -r $name.fa $PROJ/input/2
done


cd $PROJ
phylophlan.py -i 1 -t --nproc 2 2> phylo1.err

phylophlan.py -i 2 -t --nproc 2 2> phylo2.err
