#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 8
#SBATCH -J annotation-egg
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Load modules
module load bioinfo-tools eggNOG-mapper

#Load directories
export INDIR="/domus/h1/claudg/genome-project/analyses/DNA_bins_metabat"
#mkdir "/domus/h1/claudg/genome-project/analyses/DNA_egg"
export OUTDIR="/domus/h1/claudg/genome-project/analyses/DNA_egg"


cd $INDIR/2
#Load modules

module load bioinfo-tools eggNOG-mapper


#Run
echo "SRR4342133_bins.4.fa" 
emapper.py --itype metagenome -i SRR4342133_bins.4.fa -o SRR4342133_bins.4.fa --output_dir $OUTDIR/2 --override

echo "SRR4342133_bins.7.fa"
emapper.py --itype metagenome -i SRR4342133_bins.7.fa -o SRR4342133_bins.7.fa --output_dir $OUTDIR/2 --override

echo SRR4342133_bins.8.fa 
emapper.py --itype metagenome -i SRR4342133_bins.8.fa -o SRR4342133_bins.8.fa --output_dir $OUTDIR/2 --override

echo SRR4342133_bins.9.fa
emapper.py --itype metagenome -i SRR4342133_bins.9.fa -o SRR4342133_bins.9.fa --output_dir $OUTDIR/2 --override
