#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 03:00:00
#SBATCH -J fastqc-claudia
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

# FastQC quality control script for trimmed RNA

# Load modules
module load bioinfo-tools
module load FastQC/0.11.9

# Sequence directories
SEQDIR="/home/claudg/genome-project/analyses/RNA_trimmed"
OUTDIR="/home/claudg/genome-project/analyses"

# Run FastQC trimmed DNA
mkdir $OUTDIR/RNA_trimmed_fastqc
fastqc $SEQDIR/*.fastq.gz -o $OUTDIR/RNA_trimmed_fastqc/

