#!/bin/bash -l
#SBATCH -A uppmax2023-2-8
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 48:00:00
#SBATCH -J htseq
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se

#Load modules
module load bioinfo-tools
module load htseq

#Load path to files
export DATA="/home/claudg/genome-project/analyses"
BWA="$DATA/DNA_bwa"
GFF="$DATA/DNA_egg"
mkdir -p $DATA/RNA_htseq
OUTDIR=$DATA/RNA_htseq

#Expression count

cd $GFF/1
for gff in *.gff
do	
	name=$(basename "${gff}")
	bin=$(echo "$name" | cut -f1-2 -d ".")
	echo "$bin"
	htseq-count -f bam -t CDS --idattr ID -r pos -o "$OUTDIR/1/${bin}.sam" "$BWA/1/aln-sorted_${bin}.bam" "$gff"

done

cd $GFF/2
for gff in *.gff
do      
        name=$(basename "${gff}")
        bin=$(echo "$name" | cut -f1-2 -d ".")
        echo "$bin"
        htseq-count -f bam -t CDS --idattr ID -r pos -o "$OUTDIR/2/${bin}.sam" "$BWA/2/aln-sorted_${bin}.bam" "$gff"

done
