#!/bin/bash -l
#SBATCH -A uppmax2023-2-8 -M snowy
#SBATCH -p core
#SBATCH -n 6
#SBATCH -J bwa
#SBATCH -t 120:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user claudia.gonzalez-valdivia.1872@student.uu.se


#Load modules
module load bioinfo-tools
module load bwa
module load samtools

# Set paths for input and output directories
export HOME="/home/claudg/genome-project/analyses"
export INDIR="$HOME/DNA_bins_metabat"
export RNA="$HOME/RNA_trimmed"
mkdir -p "$HOME/DNA_bwa"
export OUTDIR="$HOME/DNA_bwa"

# Index reference genomes
REF="$HOME/DNA_assembled_megahit"
cd "$INDIR/1"

for ref in *.fa
do
    if [ -e "$ref" ]; then
        # Index the reference genome
        bwa index "$ref"
	
	# Define a prefix for the output files based on the reference name
        ref_prefix="${ref%.fa}"
        
        # Perform BWA alignment
        bwa mem -t 6 "$ref" "$RNA/SRR4342137.forward_paired.trimmed.fastq.gz" "$RNA/SRR4342137.reverse_paired.trimmed.fastq.gz" > "$OUTDIR/mem1_out_${ref_prefix}.sam"
        
        # Sort the SAM file using samtools
        samtools sort -@ 2 -o "$OUTDIR/aln-sorted_${ref_prefix}.bam" "$OUTDIR/mem1_out_${ref_prefix}.sam"
    fi
done

cd "$INDIR/2"

for ref in *.fa
do
    if [ -e "$ref" ]; then
        # Index the reference genome
        bwa index "$ref"

	# Define a prefix for the output files based on the reference name
        ref_prefix="${ref%.fa}"
        
        # Perform BWA alignment
        bwa mem -t 6 "$ref" "$RNA/SRR4342139.forward_paired.trimmed.fastq.gz" "$RNA/SRR4342139.reverse_paired.trimmed.fastq.gz" > "$OUTDIR/mem2_out_${ref_prefix}.sam"
        
        # Sort the SAM file using samtools
        samtools sort -@ 2 -o "$OUTDIR/aln-sorted_${ref_prefix}.bam" "$OUTDIR/mem2_out_${ref_prefix}.sam"
    fi
done

